version: "3"

services:
  benthos_client:
    image: jeffail/benthos
    container_name: client_benthos
    volumes:
      - ./config/config_benthos/client_config.yaml:/config.yaml
    command: ["-c", "/config.yaml"]
    ports:
      - "4196:4195"

  benthos_server:
    image: jeffail/benthos
    container_name: server_benthos
    volumes:
      - ./config/config_benthos/server_config.yaml:/config.yaml
    command: ["-c", "/config.yaml"]
    ports:
      - "4195:4195"