# Common config fields, showing default values
input:  
  mqtt:
    urls: 
      - mqtt://192.168.1.241:1883
    client_id: "client" 
    topics:
      - /merakimv/devices
  processors: 
    - mapping: |
        root = this
        root.notes = if (this.firmware == "v5.5") {
          "current_version"
        } else {
          "upgrade_available"
        }
    

# Common config fields, showing default values
pipeline:
  processors: []
        

# Common config fields, showing default values
output:
  mongodb:
    url: mongodb://192.168.1.241:27017
    database: "testBenthos" 
    username: "root"
    password: "example"
    collection: "devices" 
    operation: update-one
    write_concern:                      
      w: majority
      j: false
      w_timeout: ""
    upsert: true
    document_map: |-
      {"$set": {"name": this.name, "ts": this.ts, "tenant": this.tenant, "networkId": this.networkId, "firmware": this.firmware, "notes": this.notes}}
    filter_map: |-
      root.serial = this.serial
      
