# Common config fields, showing default values
input:
  label: ""
  http_server:
    address: ""
    path: /post
    allowed_verbs:
      - POST

pipeline:
  processors:
    - mapping: root = content().uppercase()

# Config fields, showing default values
output:
  label: ""
  stdout:
    codec: lines
    