version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:21.3.20.1
    container_name: ckhouse
    restart: always
    ports:
      - "9000:9000" 
      - "8123:8123"   
    volumes:
    - ./config:/var/lib/clickhouse/
    - ./config:/var/log/clickhouse-server/